apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ccd-next-hearing-date-updater App
name: ccd-next-hearing-date-updater
home: https://github.com/hmcts/ccd-next-hearing-date-updater
version: 0.0.2
maintainers:
  - name: HMCTS CCD Team
dependencies:
  - name: job
    version: ~0.7.3
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
