# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  kind: CronJob
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
