job:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  kind: CronJob
  concurrencyPolicy: Forbid
  environment:
    APPLICATIONINSIGHTS_INSTRUMENTATIONKEY: "00000000-0000-0000-0000-000000000000"
global:
  jobKind: CronJob
