version: '2.1'

services:
  ccd-next-hearing-date-updater:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ccd-next-hearing-date-updater
    container_name: ccd-next-hearing-date-updater
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      # these environment variables control the process
      - CASE_TYPES
      # these environment variables control the downstream calls
      - IDAM_API_URL
      - IDAM_S2S_URL
      - CCD_DATA_STORE_API_BASE_URL
