spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: CCD Next Hearing Date Updater
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    web-application-type: NONE
  cache:
    cache-names: nextHearingDateAdminAccessTokenCache
    caffeine:
      spec: expireAfterWrite=1800s

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ccd_next_hearing_updater
    secret:  ${CCD_NEXT_HEARING_DATE_UPDATER_SERVICE_IDAM_CLIENT_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: http://ccd-next-hearing-updater-service/oauth2redirect
  nextHearingDateSystemUser:
    username: ${IDAM_NEXT_HEARING_DATE_SYSTEM_USER:next.hearing.date.admin@gmail.com}
    password: ${IDAM_NEXT_HEARING_DATE_SYSTEM_PASSWORD:Pa55word11}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    totp_secret: ${IDAM_KEY_NEXT_HEARING_UPDATER:AAAAAAAAAAAAAAAA}
    microservice: ccd_next_hearing_updater

azure:
  application-insights:
    instrumentation-key: ${ccd.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

next-hearing-date-updater:
  csv:
    caseReferences:
      fileLocation: ${FILE_LOCATION:}
      maximumNumberOfCsvEntriesToProcess: ${MAX_CSV_RECORDS:10000}

  elasticsearch:
    querySize: ${ES_QUERY_SIZE:100}
    caseTypes: ${CASE_TYPES:}

  processing:
    enabled: ${HEARING_NEXT_DAY_CRON_JOB:true}

core_case_data:
  api:
    url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}
