spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: CCD Next Hearing Date Updater

azure:
  application-insights:
    instrumentation-key: ${ccd.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

csv:
  fileName: "${CSV_FILENAME:caseReferences.csv}"
  fileLocation: "${FILE_LOCATION}:/src/main/resources"
