spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: CCD Next Hearing Date Updater
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  security:
#    oauth2:
#      client:
#        provider:
#          oidc:
#            issuer-uri: ${IDAM_OIDC_URL:http://localhost:5000}/o
#        registration:
#          oidc:
#            client-id: internal
#            client-secret: internal
  cache:
    cache-names: nextHearingDateAdminAccessTokenCache
    caffeine:
      spec: expireAfterWrite=1800s

idam:
  api:
    url: ${IDAM_API_URL:http://localhost:5000}
  client:
    id: ccd-next-hearing-date-updater
    secret:  ${CCD_NEXT_HEARING_DATE_UPDATER_SERVICE_IDAM_CLIENT_SECRET:AAAAAAAAAAAAAAAA}
    redirect_uri: http://localhost:4561/oauth2redirect
  nextHearingDateSystemUser:
    username: ${IDAM_NEXT_HEARING_DATE_SYSTEM_USER:next.hearing.date.admin@gmail.com}
    password: ${IDAM_NEXT_HEARING_DATE_SYSTEM_PASSWORD:Pa55word11}
  s2s-auth:
    url: ${IDAM_S2S_URL:http://localhost:4502}
    totp_secret: ${IDAM_KEY_NEXT_HEARING_UPDATER:AAAAAAAAAAAAAAAA}
    microservice: ccd-next-hearing-updater-service

azure:
  application-insights:
    instrumentation-key: ${ccd.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

core_case_data:
  api:
    url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}

csv:
  caseReferences:
    fileName: ${CSV_FILENAME:caseReferences.csv}
    fileLocation: ${FILE_LOCATION:/src/main/resources}
  caseTypes: ${CASE_TYPES:}

elasticsearch:
  querySize: ${ES_QUERY_SIZE:100}

cronjob:
  enabled: ${CRON_JOB_ENABLED:true}

