spring:
  config:
    import: "optional:configtree:/mnt/secrets/ccd/"
  application:
    name: CCD Next Hearing Date Updater
  main:
    web-application-type: NONE
  cache:
    cache-names: nextHearingDateAdminAccessTokenCache
    caffeine:
      spec: expireAfterWrite=1800s

azure:
  application-insights:
    instrumentation-key: ${ccd.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}

next-hearing-date-updater:
  csv:
    caseReferences:
      fileLocation: ${FILE_LOCATION:}
      maximumNumberOfCsvEntriesToProcess: ${MAX_CSV_RECORDS:10000}

  elasticsearch:
    host: "http://localhost:1234"
    caseTypes: ${CASE_TYPES:}

  processing:
    enabled: true

core_case_data:
  api:
    url: ${CCD_DATA_STORE_API_BASE_URL:http://localhost:4452}
