spring:
  main:
    allow-circular-references: true

core_case_data:
  api:
    url: http://localhost:${wiremock.server.port:4452}

next-hearing-date-updater:
  processing:
    enabled: false

idam:
  api:
    url: http://localhost:${wiremock.server.port:5000}
  s2s-auth:
    url: http://localhost:${wiremock.server.port:5000}/s2s

elasticsearch:
  hosts: ${ELASTIC_SEARCH_DATA_NODES_HOSTS:"http://localhost:4578"}
